### ISSUE TITLE
feat: Allow only logged user's to user app functionalities

### ISSUE THREAD

**Issue by vicap-staina** [vicap-staina/vicap#6]

**Comment by leohck** [comment]
- [x] bem-vindo
- [x] home
- [ ] confirmacao-deposito-saco
- [ ] confirmacao-deposito-saco-2
- [ ] lista-promocoes-convertidas
- [ ] lista-recompensas
- [ ] lojas-recompensas
- [ ] mapa-pontos
- [ ] perfil-usuario
- [ ] pontos-coletas
- [ ] scanner
- [ ] scanner-deixe-bolsa
- [ ] scanner-ponto
- [ ] scanner-ponto-acao
- [ ] scanner-saco-como-funciona
- [ ] scanner-saco-erro
- [ ] scanner-saco-identificacao-1
- [ ] scanner-saco-identificacao-2
- [ ] scanner-saco-identificacao-3
- [ ] scanner-saco-qrcode
- [ ] scanner-saco-sucesso
- [ ] scanner-saco-validacao
- [ ] scanner-voce-ganhou

**Comment by leohck** [comment]
done
